// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: rockbox/v1alpha1/device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - rockbox.v1alpha1.DeviceService

/// Namespace containing generated types for the "rockbox.v1alpha1.DeviceService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Rockbox_V1alpha1_DeviceService: Sendable {
    /// Service descriptor for the "rockbox.v1alpha1.DeviceService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Namespace for "GetDevices" metadata.
        internal enum GetDevices: Sendable {
            /// Request type for "GetDevices".
            internal typealias Input = Rockbox_V1alpha1_GetDevicesRequest
            /// Response type for "GetDevices".
            internal typealias Output = Rockbox_V1alpha1_GetDevicesResponse
            /// Descriptor for "GetDevices".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService"),
                method: "GetDevices"
            )
        }
        /// Namespace for "GetDevice" metadata.
        internal enum GetDevice: Sendable {
            /// Request type for "GetDevice".
            internal typealias Input = Rockbox_V1alpha1_GetDeviceRequest
            /// Response type for "GetDevice".
            internal typealias Output = Rockbox_V1alpha1_GetDeviceResponse
            /// Descriptor for "GetDevice".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService"),
                method: "GetDevice"
            )
        }
        /// Namespace for "ConnectDevice" metadata.
        internal enum ConnectDevice: Sendable {
            /// Request type for "ConnectDevice".
            internal typealias Input = Rockbox_V1alpha1_ConnectDeviceRequest
            /// Response type for "ConnectDevice".
            internal typealias Output = Rockbox_V1alpha1_ConnectDeviceResponse
            /// Descriptor for "ConnectDevice".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService"),
                method: "ConnectDevice"
            )
        }
        /// Namespace for "DisconnectDevice" metadata.
        internal enum DisconnectDevice: Sendable {
            /// Request type for "DisconnectDevice".
            internal typealias Input = Rockbox_V1alpha1_DisconnectDeviceRequest
            /// Response type for "DisconnectDevice".
            internal typealias Output = Rockbox_V1alpha1_DisconnectDeviceResponse
            /// Descriptor for "DisconnectDevice".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService"),
                method: "DisconnectDevice"
            )
        }
        /// Descriptors for all methods in the "rockbox.v1alpha1.DeviceService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetDevices.descriptor,
            GetDevice.descriptor,
            ConnectDevice.descriptor,
            DisconnectDevice.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "rockbox.v1alpha1.DeviceService" service.
    internal static let rockbox_v1Alpha1_DeviceService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.DeviceService")
}

// MARK: rockbox.v1alpha1.DeviceService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService {
    /// Streaming variant of the service protocol for the "rockbox.v1alpha1.DeviceService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetDevices" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Rockbox_V1alpha1_GetDevicesRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Rockbox_V1alpha1_GetDevicesResponse` messages.
        func getDevices(
            request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_GetDevicesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_GetDevicesResponse>

        /// Handle the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Rockbox_V1alpha1_GetDeviceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Rockbox_V1alpha1_GetDeviceResponse` messages.
        func getDevice(
            request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_GetDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_GetDeviceResponse>

        /// Handle the "ConnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Rockbox_V1alpha1_ConnectDeviceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Rockbox_V1alpha1_ConnectDeviceResponse` messages.
        func connectDevice(
            request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_ConnectDeviceResponse>

        /// Handle the "DisconnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Rockbox_V1alpha1_DisconnectDeviceRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Rockbox_V1alpha1_DisconnectDeviceResponse` messages.
        func disconnectDevice(
            request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>
    }

    /// Service protocol for the "rockbox.v1alpha1.DeviceService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Rockbox_V1alpha1_DeviceService.StreamingServiceProtocol {
        /// Handle the "GetDevices" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDevicesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Rockbox_V1alpha1_GetDevicesResponse` message.
        func getDevices(
            request: GRPCCore.ServerRequest<Rockbox_V1alpha1_GetDevicesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDevicesResponse>

        /// Handle the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Rockbox_V1alpha1_GetDeviceResponse` message.
        func getDevice(
            request: GRPCCore.ServerRequest<Rockbox_V1alpha1_GetDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDeviceResponse>

        /// Handle the "ConnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_ConnectDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Rockbox_V1alpha1_ConnectDeviceResponse` message.
        func connectDevice(
            request: GRPCCore.ServerRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_ConnectDeviceResponse>

        /// Handle the "DisconnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_DisconnectDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Rockbox_V1alpha1_DisconnectDeviceResponse` message.
        func disconnectDevice(
            request: GRPCCore.ServerRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>
    }

    /// Simple service protocol for the "rockbox.v1alpha1.DeviceService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Rockbox_V1alpha1_DeviceService.ServiceProtocol {
        /// Handle the "GetDevices" method.
        ///
        /// - Parameters:
        ///   - request: A `Rockbox_V1alpha1_GetDevicesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Rockbox_V1alpha1_GetDevicesResponse` to respond with.
        func getDevices(
            request: Rockbox_V1alpha1_GetDevicesRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Rockbox_V1alpha1_GetDevicesResponse

        /// Handle the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A `Rockbox_V1alpha1_GetDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Rockbox_V1alpha1_GetDeviceResponse` to respond with.
        func getDevice(
            request: Rockbox_V1alpha1_GetDeviceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Rockbox_V1alpha1_GetDeviceResponse

        /// Handle the "ConnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A `Rockbox_V1alpha1_ConnectDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Rockbox_V1alpha1_ConnectDeviceResponse` to respond with.
        func connectDevice(
            request: Rockbox_V1alpha1_ConnectDeviceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Rockbox_V1alpha1_ConnectDeviceResponse

        /// Handle the "DisconnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A `Rockbox_V1alpha1_DisconnectDeviceRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Rockbox_V1alpha1_DisconnectDeviceResponse` to respond with.
        func disconnectDevice(
            request: Rockbox_V1alpha1_DisconnectDeviceRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Rockbox_V1alpha1_DisconnectDeviceResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Rockbox_V1alpha1_DeviceService.Method.GetDevices.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetDevicesRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetDevicesResponse>(),
            handler: { request, context in
                try await self.getDevices(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Rockbox_V1alpha1_DeviceService.Method.GetDevice.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetDeviceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetDeviceResponse>(),
            handler: { request, context in
                try await self.getDevice(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Rockbox_V1alpha1_DeviceService.Method.ConnectDevice.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_ConnectDeviceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_ConnectDeviceResponse>(),
            handler: { request, context in
                try await self.connectDevice(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Rockbox_V1alpha1_DeviceService.Method.DisconnectDevice.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_DisconnectDeviceRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_DisconnectDeviceResponse>(),
            handler: { request, context in
                try await self.disconnectDevice(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService.ServiceProtocol {
    internal func getDevices(
        request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_GetDevicesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_GetDevicesResponse> {
        let response = try await self.getDevices(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func getDevice(
        request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_GetDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_GetDeviceResponse> {
        let response = try await self.getDevice(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func connectDevice(
        request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_ConnectDeviceResponse> {
        let response = try await self.connectDevice(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    internal func disconnectDevice(
        request: GRPCCore.StreamingServerRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Rockbox_V1alpha1_DisconnectDeviceResponse> {
        let response = try await self.disconnectDevice(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService.SimpleServiceProtocol {
    internal func getDevices(
        request: GRPCCore.ServerRequest<Rockbox_V1alpha1_GetDevicesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDevicesResponse> {
        return GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDevicesResponse>(
            message: try await self.getDevices(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func getDevice(
        request: GRPCCore.ServerRequest<Rockbox_V1alpha1_GetDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDeviceResponse> {
        return GRPCCore.ServerResponse<Rockbox_V1alpha1_GetDeviceResponse>(
            message: try await self.getDevice(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func connectDevice(
        request: GRPCCore.ServerRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_ConnectDeviceResponse> {
        return GRPCCore.ServerResponse<Rockbox_V1alpha1_ConnectDeviceResponse>(
            message: try await self.connectDevice(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    internal func disconnectDevice(
        request: GRPCCore.ServerRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Rockbox_V1alpha1_DisconnectDeviceResponse> {
        return GRPCCore.ServerResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>(
            message: try await self.disconnectDevice(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: rockbox.v1alpha1.DeviceService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService {
    /// Generated client protocol for the "rockbox.v1alpha1.DeviceService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "GetDevices" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDevicesRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_GetDevicesRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_GetDevicesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getDevices<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDevicesRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetDevicesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetDevicesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDevicesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_GetDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_GetDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetDeviceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDeviceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ConnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_ConnectDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_ConnectDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_ConnectDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func connectDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_ConnectDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_ConnectDeviceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_ConnectDeviceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DisconnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_DisconnectDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_DisconnectDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_DisconnectDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func disconnectDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_DisconnectDeviceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "rockbox.v1alpha1.DeviceService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetDevices" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDevicesRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_GetDevicesRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_GetDevicesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getDevices<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDevicesRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetDevicesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetDevicesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDevicesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_DeviceService.Method.GetDevices.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_GetDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_GetDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_GetDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetDeviceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDeviceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_DeviceService.Method.GetDevice.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ConnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_ConnectDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_ConnectDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_ConnectDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func connectDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_ConnectDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_ConnectDeviceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_ConnectDeviceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_DeviceService.Method.ConnectDevice.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DisconnectDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Rockbox_V1alpha1_DisconnectDeviceRequest` message.
        ///   - serializer: A serializer for `Rockbox_V1alpha1_DisconnectDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Rockbox_V1alpha1_DisconnectDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func disconnectDevice<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_DisconnectDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_DisconnectDeviceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_DeviceService.Method.DisconnectDevice.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService.ClientProtocol {
    /// Call the "GetDevices" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Rockbox_V1alpha1_GetDevicesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getDevices<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDevicesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDevicesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getDevices(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetDevicesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetDevicesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDevice" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Rockbox_V1alpha1_GetDeviceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getDevice<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDeviceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getDevice(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetDeviceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetDeviceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ConnectDevice" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Rockbox_V1alpha1_ConnectDeviceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func connectDevice<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_ConnectDeviceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_ConnectDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.connectDevice(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_ConnectDeviceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_ConnectDeviceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DisconnectDevice" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Rockbox_V1alpha1_DisconnectDeviceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func disconnectDevice<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.disconnectDevice(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_DisconnectDeviceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_DisconnectDeviceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_DeviceService.ClientProtocol {
    /// Call the "GetDevices" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getDevices<Result>(
        _ message: Rockbox_V1alpha1_GetDevicesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDevicesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDevicesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getDevices(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDevice" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getDevice<Result>(
        _ message: Rockbox_V1alpha1_GetDeviceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetDeviceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getDevice(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ConnectDevice" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func connectDevice<Result>(
        _ message: Rockbox_V1alpha1_ConnectDeviceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_ConnectDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_ConnectDeviceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.connectDevice(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DisconnectDevice" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func disconnectDevice<Result>(
        _ message: Rockbox_V1alpha1_DisconnectDeviceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DisconnectDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_DisconnectDeviceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.disconnectDevice(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}