// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: rockbox/v1alpha1/metadata.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - rockbox.v1alpha1.MetadataService

/// Namespace containing generated types for the "rockbox.v1alpha1.MetadataService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Rockbox_V1alpha1_MetadataService: Sendable {
    /// Service descriptor for the "rockbox.v1alpha1.MetadataService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.MetadataService")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Descriptors for all methods in the "rockbox.v1alpha1.MetadataService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = []
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "rockbox.v1alpha1.MetadataService" service.
    internal static let rockbox_v1Alpha1_MetadataService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.MetadataService")
}

// MARK: rockbox.v1alpha1.MetadataService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService {
    /// Streaming variant of the service protocol for the "rockbox.v1alpha1.MetadataService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {}

    /// Service protocol for the "rockbox.v1alpha1.MetadataService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: Rockbox_V1alpha1_MetadataService.StreamingServiceProtocol {}

    /// Simple service protocol for the "rockbox.v1alpha1.MetadataService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: Rockbox_V1alpha1_MetadataService.ServiceProtocol {}
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {}
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService.ServiceProtocol {
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService.SimpleServiceProtocol {
}

// MARK: rockbox.v1alpha1.MetadataService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService {
    /// Generated client protocol for the "rockbox.v1alpha1.MetadataService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {}

    /// Generated client for the "rockbox.v1alpha1.MetadataService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService.ClientProtocol {
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_MetadataService.ClientProtocol {
}