// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: rockbox/v1alpha1/smart_playlist.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - rockbox.v1alpha1.SmartPlaylistService

/// Namespace containing generated types for the "rockbox.v1alpha1.SmartPlaylistService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
internal enum Rockbox_V1alpha1_SmartPlaylistService: Sendable {
    /// Service descriptor for the "rockbox.v1alpha1.SmartPlaylistService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService")
    /// Namespace for method metadata.
    internal enum Method: Sendable {
        /// Namespace for "GetSmartPlaylists" metadata.
        internal enum GetSmartPlaylists: Sendable {
            /// Request type for "GetSmartPlaylists".
            internal typealias Input = Rockbox_V1alpha1_GetSmartPlaylistsRequest
            /// Response type for "GetSmartPlaylists".
            internal typealias Output = Rockbox_V1alpha1_GetSmartPlaylistsResponse
            /// Descriptor for "GetSmartPlaylists".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "GetSmartPlaylists"
            )
        }
        /// Namespace for "GetSmartPlaylist" metadata.
        internal enum GetSmartPlaylist: Sendable {
            /// Request type for "GetSmartPlaylist".
            internal typealias Input = Rockbox_V1alpha1_GetSmartPlaylistRequest
            /// Response type for "GetSmartPlaylist".
            internal typealias Output = Rockbox_V1alpha1_GetSmartPlaylistResponse
            /// Descriptor for "GetSmartPlaylist".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "GetSmartPlaylist"
            )
        }
        /// Namespace for "CreateSmartPlaylist" metadata.
        internal enum CreateSmartPlaylist: Sendable {
            /// Request type for "CreateSmartPlaylist".
            internal typealias Input = Rockbox_V1alpha1_CreateSmartPlaylistRequest
            /// Response type for "CreateSmartPlaylist".
            internal typealias Output = Rockbox_V1alpha1_CreateSmartPlaylistResponse
            /// Descriptor for "CreateSmartPlaylist".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "CreateSmartPlaylist"
            )
        }
        /// Namespace for "UpdateSmartPlaylist" metadata.
        internal enum UpdateSmartPlaylist: Sendable {
            /// Request type for "UpdateSmartPlaylist".
            internal typealias Input = Rockbox_V1alpha1_UpdateSmartPlaylistRequest
            /// Response type for "UpdateSmartPlaylist".
            internal typealias Output = Rockbox_V1alpha1_UpdateSmartPlaylistResponse
            /// Descriptor for "UpdateSmartPlaylist".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "UpdateSmartPlaylist"
            )
        }
        /// Namespace for "DeleteSmartPlaylist" metadata.
        internal enum DeleteSmartPlaylist: Sendable {
            /// Request type for "DeleteSmartPlaylist".
            internal typealias Input = Rockbox_V1alpha1_DeleteSmartPlaylistRequest
            /// Response type for "DeleteSmartPlaylist".
            internal typealias Output = Rockbox_V1alpha1_DeleteSmartPlaylistResponse
            /// Descriptor for "DeleteSmartPlaylist".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "DeleteSmartPlaylist"
            )
        }
        /// Namespace for "GetSmartPlaylistTracks" metadata.
        internal enum GetSmartPlaylistTracks: Sendable {
            /// Request type for "GetSmartPlaylistTracks".
            internal typealias Input = Rockbox_V1alpha1_GetSmartPlaylistTracksRequest
            /// Response type for "GetSmartPlaylistTracks".
            internal typealias Output = Rockbox_V1alpha1_GetSmartPlaylistTracksResponse
            /// Descriptor for "GetSmartPlaylistTracks".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "GetSmartPlaylistTracks"
            )
        }
        /// Namespace for "PlaySmartPlaylist" metadata.
        internal enum PlaySmartPlaylist: Sendable {
            /// Request type for "PlaySmartPlaylist".
            internal typealias Input = Rockbox_V1alpha1_PlaySmartPlaylistRequest
            /// Response type for "PlaySmartPlaylist".
            internal typealias Output = Rockbox_V1alpha1_PlaySmartPlaylistResponse
            /// Descriptor for "PlaySmartPlaylist".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "PlaySmartPlaylist"
            )
        }
        /// Namespace for "RecordTrackPlayed" metadata.
        internal enum RecordTrackPlayed: Sendable {
            /// Request type for "RecordTrackPlayed".
            internal typealias Input = Rockbox_V1alpha1_RecordTrackPlayedRequest
            /// Response type for "RecordTrackPlayed".
            internal typealias Output = Rockbox_V1alpha1_RecordTrackPlayedResponse
            /// Descriptor for "RecordTrackPlayed".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "RecordTrackPlayed"
            )
        }
        /// Namespace for "RecordTrackSkipped" metadata.
        internal enum RecordTrackSkipped: Sendable {
            /// Request type for "RecordTrackSkipped".
            internal typealias Input = Rockbox_V1alpha1_RecordTrackSkippedRequest
            /// Response type for "RecordTrackSkipped".
            internal typealias Output = Rockbox_V1alpha1_RecordTrackSkippedResponse
            /// Descriptor for "RecordTrackSkipped".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "RecordTrackSkipped"
            )
        }
        /// Namespace for "GetTrackStats" metadata.
        internal enum GetTrackStats: Sendable {
            /// Request type for "GetTrackStats".
            internal typealias Input = Rockbox_V1alpha1_GetTrackStatsRequest
            /// Response type for "GetTrackStats".
            internal typealias Output = Rockbox_V1alpha1_GetTrackStatsResponse
            /// Descriptor for "GetTrackStats".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService"),
                method: "GetTrackStats"
            )
        }
        /// Descriptors for all methods in the "rockbox.v1alpha1.SmartPlaylistService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetSmartPlaylists.descriptor,
            GetSmartPlaylist.descriptor,
            CreateSmartPlaylist.descriptor,
            UpdateSmartPlaylist.descriptor,
            DeleteSmartPlaylist.descriptor,
            GetSmartPlaylistTracks.descriptor,
            PlaySmartPlaylist.descriptor,
            RecordTrackPlayed.descriptor,
            RecordTrackSkipped.descriptor,
            GetTrackStats.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "rockbox.v1alpha1.SmartPlaylistService" service.
    internal static let rockbox_v1Alpha1_SmartPlaylistService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "rockbox.v1alpha1.SmartPlaylistService")
}

// MARK: rockbox.v1alpha1.SmartPlaylistService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_SmartPlaylistService {
    /// Generated client protocol for the "rockbox.v1alpha1.SmartPlaylistService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "GetSmartPlaylists" method.
        func getSmartPlaylists<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistsRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetSmartPlaylist" method.
        func getSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CreateSmartPlaylist" method.
        func createSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_CreateSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_CreateSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_CreateSmartPlaylistResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_CreateSmartPlaylistResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateSmartPlaylist" method.
        func updateSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteSmartPlaylist" method.
        func deleteSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetSmartPlaylistTracks" method.
        func getSmartPlaylistTracks<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "PlaySmartPlaylist" method.
        func playSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_PlaySmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_PlaySmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_PlaySmartPlaylistResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_PlaySmartPlaylistResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RecordTrackPlayed" method.
        func recordTrackPlayed<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackPlayedRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_RecordTrackPlayedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_RecordTrackPlayedResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackPlayedResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RecordTrackSkipped" method.
        func recordTrackSkipped<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackSkippedRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_RecordTrackSkippedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_RecordTrackSkippedResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackSkippedResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetTrackStats" method.
        func getTrackStats<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetTrackStatsRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetTrackStatsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetTrackStatsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetTrackStatsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "rockbox.v1alpha1.SmartPlaylistService" service.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        internal func getSmartPlaylists<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistsRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.GetSmartPlaylists.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func getSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.GetSmartPlaylist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func createSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_CreateSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_CreateSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_CreateSmartPlaylistResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_CreateSmartPlaylistResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.CreateSmartPlaylist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func updateSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.UpdateSmartPlaylist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func deleteSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.DeleteSmartPlaylist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func getSmartPlaylistTracks<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.GetSmartPlaylistTracks.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func playSmartPlaylist<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_PlaySmartPlaylistRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_PlaySmartPlaylistRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_PlaySmartPlaylistResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_PlaySmartPlaylistResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.PlaySmartPlaylist.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func recordTrackPlayed<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackPlayedRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_RecordTrackPlayedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_RecordTrackPlayedResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackPlayedResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.RecordTrackPlayed.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func recordTrackSkipped<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackSkippedRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_RecordTrackSkippedRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_RecordTrackSkippedResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackSkippedResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.RecordTrackSkipped.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        internal func getTrackStats<Result>(
            request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetTrackStatsRequest>,
            serializer: some GRPCCore.MessageSerializer<Rockbox_V1alpha1_GetTrackStatsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Rockbox_V1alpha1_GetTrackStatsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetTrackStatsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Rockbox_V1alpha1_SmartPlaylistService.Method.GetTrackStats.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_SmartPlaylistService.ClientProtocol {
    internal func getSmartPlaylists<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getSmartPlaylists(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetSmartPlaylistsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetSmartPlaylistsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getSmartPlaylist<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getSmartPlaylist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetSmartPlaylistRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetSmartPlaylistResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func createSmartPlaylist<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_CreateSmartPlaylistRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_CreateSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createSmartPlaylist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_CreateSmartPlaylistRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_CreateSmartPlaylistResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func updateSmartPlaylist<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateSmartPlaylist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func deleteSmartPlaylist<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteSmartPlaylist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getSmartPlaylistTracks<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getSmartPlaylistTracks(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func playSmartPlaylist<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_PlaySmartPlaylistRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_PlaySmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.playSmartPlaylist(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_PlaySmartPlaylistRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_PlaySmartPlaylistResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func recordTrackPlayed<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackPlayedRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackPlayedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.recordTrackPlayed(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_RecordTrackPlayedRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_RecordTrackPlayedResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func recordTrackSkipped<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackSkippedRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackSkippedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.recordTrackSkipped(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_RecordTrackSkippedRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_RecordTrackSkippedResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getTrackStats<Result>(
        request: GRPCCore.ClientRequest<Rockbox_V1alpha1_GetTrackStatsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetTrackStatsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getTrackStats(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Rockbox_V1alpha1_GetTrackStatsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Rockbox_V1alpha1_GetTrackStatsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Rockbox_V1alpha1_SmartPlaylistService.ClientProtocol {
    internal func getSmartPlaylists<Result>(
        _ message: Rockbox_V1alpha1_GetSmartPlaylistsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getSmartPlaylists(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getSmartPlaylist<Result>(
        _ message: Rockbox_V1alpha1_GetSmartPlaylistRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getSmartPlaylist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func createSmartPlaylist<Result>(
        _ message: Rockbox_V1alpha1_CreateSmartPlaylistRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_CreateSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_CreateSmartPlaylistRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createSmartPlaylist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func updateSmartPlaylist<Result>(
        _ message: Rockbox_V1alpha1_UpdateSmartPlaylistRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_UpdateSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_UpdateSmartPlaylistRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateSmartPlaylist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func deleteSmartPlaylist<Result>(
        _ message: Rockbox_V1alpha1_DeleteSmartPlaylistRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_DeleteSmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_DeleteSmartPlaylistRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteSmartPlaylist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getSmartPlaylistTracks<Result>(
        _ message: Rockbox_V1alpha1_GetSmartPlaylistTracksRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetSmartPlaylistTracksResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetSmartPlaylistTracksRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getSmartPlaylistTracks(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func playSmartPlaylist<Result>(
        _ message: Rockbox_V1alpha1_PlaySmartPlaylistRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_PlaySmartPlaylistResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_PlaySmartPlaylistRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.playSmartPlaylist(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func recordTrackPlayed<Result>(
        _ message: Rockbox_V1alpha1_RecordTrackPlayedRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackPlayedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackPlayedRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.recordTrackPlayed(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func recordTrackSkipped<Result>(
        _ message: Rockbox_V1alpha1_RecordTrackSkippedRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_RecordTrackSkippedResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_RecordTrackSkippedRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.recordTrackSkipped(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    internal func getTrackStats<Result>(
        _ message: Rockbox_V1alpha1_GetTrackStatsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Rockbox_V1alpha1_GetTrackStatsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Rockbox_V1alpha1_GetTrackStatsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getTrackStats(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}
