// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: rockbox/v1alpha1/system.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct Rockbox_V1alpha1_GetRockboxVersionRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Rockbox_V1alpha1_GetRockboxVersionResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var version: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Rockbox_V1alpha1_GetGlobalStatusRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Rockbox_V1alpha1_GetGlobalStatusResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var resumeIndex: Int32 = 0

  var resumeCrc32: UInt32 = 0

  var resumeElapsed: UInt32 = 0

  var resumeOffset: UInt32 = 0

  var runtime: Int32 = 0

  var topruntime: Int32 = 0

  var dircacheSize: Int32 = 0

  var lastScreen: Int32 = 0

  var viewerIconCount: Int32 = 0

  var lastVolumeChange: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "rockbox.v1alpha1"

extension Rockbox_V1alpha1_GetRockboxVersionRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRockboxVersionRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Rockbox_V1alpha1_GetRockboxVersionRequest, rhs: Rockbox_V1alpha1_GetRockboxVersionRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rockbox_V1alpha1_GetRockboxVersionResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetRockboxVersionResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}version\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.version) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.version.isEmpty {
      try visitor.visitSingularStringField(value: self.version, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Rockbox_V1alpha1_GetRockboxVersionResponse, rhs: Rockbox_V1alpha1_GetRockboxVersionResponse) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rockbox_V1alpha1_GetGlobalStatusRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetGlobalStatusRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Rockbox_V1alpha1_GetGlobalStatusRequest, rhs: Rockbox_V1alpha1_GetGlobalStatusRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Rockbox_V1alpha1_GetGlobalStatusResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GetGlobalStatusResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}resume_index\0\u{3}resume_crc32\0\u{3}resume_elapsed\0\u{3}resume_offset\0\u{1}runtime\0\u{1}topruntime\0\u{3}dircache_size\0\u{3}last_screen\0\u{3}viewer_icon_count\0\u{3}last_volume_change\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.resumeIndex) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.resumeCrc32) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.resumeElapsed) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.resumeOffset) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.runtime) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.topruntime) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.dircacheSize) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.lastScreen) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.viewerIconCount) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.lastVolumeChange) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.resumeIndex != 0 {
      try visitor.visitSingularInt32Field(value: self.resumeIndex, fieldNumber: 1)
    }
    if self.resumeCrc32 != 0 {
      try visitor.visitSingularUInt32Field(value: self.resumeCrc32, fieldNumber: 2)
    }
    if self.resumeElapsed != 0 {
      try visitor.visitSingularUInt32Field(value: self.resumeElapsed, fieldNumber: 3)
    }
    if self.resumeOffset != 0 {
      try visitor.visitSingularUInt32Field(value: self.resumeOffset, fieldNumber: 4)
    }
    if self.runtime != 0 {
      try visitor.visitSingularInt32Field(value: self.runtime, fieldNumber: 5)
    }
    if self.topruntime != 0 {
      try visitor.visitSingularInt32Field(value: self.topruntime, fieldNumber: 6)
    }
    if self.dircacheSize != 0 {
      try visitor.visitSingularInt32Field(value: self.dircacheSize, fieldNumber: 7)
    }
    if self.lastScreen != 0 {
      try visitor.visitSingularInt32Field(value: self.lastScreen, fieldNumber: 8)
    }
    if self.viewerIconCount != 0 {
      try visitor.visitSingularInt32Field(value: self.viewerIconCount, fieldNumber: 9)
    }
    if self.lastVolumeChange != 0 {
      try visitor.visitSingularInt32Field(value: self.lastVolumeChange, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Rockbox_V1alpha1_GetGlobalStatusResponse, rhs: Rockbox_V1alpha1_GetGlobalStatusResponse) -> Bool {
    if lhs.resumeIndex != rhs.resumeIndex {return false}
    if lhs.resumeCrc32 != rhs.resumeCrc32 {return false}
    if lhs.resumeElapsed != rhs.resumeElapsed {return false}
    if lhs.resumeOffset != rhs.resumeOffset {return false}
    if lhs.runtime != rhs.runtime {return false}
    if lhs.topruntime != rhs.topruntime {return false}
    if lhs.dircacheSize != rhs.dircacheSize {return false}
    if lhs.lastScreen != rhs.lastScreen {return false}
    if lhs.viewerIconCount != rhs.viewerIconCount {return false}
    if lhs.lastVolumeChange != rhs.lastVolumeChange {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
