FROM rust:1.94-bookworm AS builder

ARG TARGETARCH

ARG GITHUB_TOKEN

ARG TAG

ENV GITHUB_ACCESS_TOKEN=${GITHUB_TOKEN}

ENV GH_TOKEN=${GITHUB_TOKEN}

ENV TAG=${TAG}

RUN apt-get update && apt-get install -y build-essential \
  libsdl2-dev \
  libfreetype6-dev \
  libunwind-dev \
  libdbus-1-dev \
  curl \
  wget \
  zip \
  unzip \
  protobuf-compiler \
  cmake

RUN case "${TARGETARCH}" in \
      amd64) ZIG_ARCH="x86_64" ;; \
      arm64) ZIG_ARCH="aarch64" ;; \
      *) echo "Unsupported arch: ${TARGETARCH}" && exit 1 ;; \
    esac && \
    export VERSION=0.16.0 && \
    wget "https://ziglang.org/download/${VERSION}/zig-${ZIG_ARCH}-linux-${VERSION}.tar.xz" && \
    tar -xf "zig-${ZIG_ARCH}-linux-${VERSION}.tar.xz" && \
    mv "zig-${ZIG_ARCH}-linux-${VERSION}" /usr/local/zig && \
    ln -s /usr/local/zig/zig /usr/local/bin/zig

RUN curl -Ssf https://pkgx.sh | sh

RUN pkgm install buf deno

COPY . /app

WORKDIR /app

RUN mkdir -p build

WORKDIR /app/webui/rockbox

RUN deno install

RUN deno run build

WORKDIR /app/build-lib

RUN ../tools/configure --target=sdlapp --type=N --lcdwidth=320 --lcdheight=240 --prefix=/usr/local && cp ../autoconf/autoconf.h .

RUN make -j$(nproc) lib
