music_dir    = "/root/Music"
audio_output = "fifo"         # pipe PCM to snapserver via named FIFO
fifo_path    = "/tmp/rockbox.fifo"
playlist_shuffle = false
repeat_mode = 1
bass = 2
treble = 8
bass_cutoff = 0
treble_cutoff = 0
crossfade = 5
fade_on_stop = false
fade_in_delay = 2
fade_in_duration = 7
fade_out_delay = 4
fade_out_duration = 0
fade_out_mixmode = 2
balance = 0
stereo_width = 100
stereosw_mode = 0
surround_enabled = 0
surround_balance = 0
surround_fx1 = 0
surround_fx2 = 0
party_mode = true
channel_config = 0
player_name = ""
eq_enabled = true

[[eq_band_settings]]
cutoff = 60
q = 70
gain = 55

[[eq_band_settings]]
cutoff = 200
q = 70
gain = 100

[[eq_band_settings]]
cutoff = 500
q = 70
gain = 90

[[eq_band_settings]]
cutoff = 1000
q = 70
gain = -70

[[eq_band_settings]]
cutoff = 2000
q = 70
gain = -25

[[eq_band_settings]]
cutoff = 4000
q = 70
gain = -10

[[eq_band_settings]]
cutoff = 7000
q = 70
gain = 30

[[eq_band_settings]]
cutoff = 10000
q = 70
gain = 50

[[eq_band_settings]]
cutoff = 14000
q = 70
gain = 65

[[eq_band_settings]]
cutoff = 20000
q = 70
gain = 75

[replaygain_settings]
noclip = true
type = 0
preamp = 0

[compressor_settings]
threshold = -24
makeup_gain = 0
ratio = 4
knee = 1
release_time = 300
attack_time = 5
