pub const PLAYLIST_INSERT_FIRST: i32 = -4;
pub const PLAYLIST_INSERT_LAST: i32 = -3;
pub const DECODERS: &str = r#"plugin: mpg123
suffix: mp3
plugin: vorbis
suffix: ogg
suffix: oga
mime_type: application/ogg
mime_type: application/x-ogg
mime_type: audio/ogg
mime_type: audio/vorbis
mime_type: audio/vorbis+ogg
mime_type: audio/x-ogg
mime_type: audio/x-vorbis
mime_type: audio/x-vorbis+ogg
plugin: oggflac
suffix: ogg
suffix: oga
mime_type: application/ogg
mime_type: application/x-ogg
mime_type: audio/ogg
mime_type: audio/x-flac+ogg
mime_type: audio/x-ogg
plugin: flac
suffix: flac
mime_type: application/flac
mime_type: application/x-flac
mime_type: audio/flac
mime_type: audio/x-flac
plugin: opus
suffix: opus
suffix: ogg
suffix: oga
mime_type: audio/ogg
mime_type: application/ogg
mime_type: audio/opus
plugin: sndfile
suffix: wav
suffix: aiff
suffix: aif
suffix: au
suffix: snd
suffix: paf
suffix: iff
suffix: svx
suffix: sf
suffix: voc
suffix: w64
suffix: pvf
suffix: xi
suffix: htk
suffix: caf
suffix: sd2
mime_type: audio/wav
mime_type: audio/aiff
mime_type: audio/x-wav
mime_type: audio/x-aiff
plugin: dsdiff
suffix: dff
mime_type: application/x-dff
mime_type: audio/x-dff
mime_type: audio/x-dsd
plugin: dsf
suffix: dsf
mime_type: application/x-dsf
mime_type: audio/x-dsf
mime_type: audio/x-dsd
plugin: faad
suffix: aac
mime_type: audio/aac
mime_type: audio/aacp
plugin: wavpack
suffix: wv
mime_type: audio/x-wavpack
plugin: fluidsynth
suffix: mid
plugin: ffmpeg
suffix: 16sv
suffix: 3g2
suffix: 3gp
suffix: 4xm
suffix: 8svx
suffix: aa3
suffix: aac
suffix: ac3
suffix: adx
suffix: afc
suffix: aif
suffix: aifc
suffix: aiff
suffix: al
suffix: alaw
suffix: amr
suffix: anim
suffix: apc
suffix: ape
suffix: asf
suffix: atrac
suffix: au
suffix: aud
suffix: avi
suffix: avm2
suffix: avs
suffix: bap
suffix: bfi
suffix: c93
suffix: cak
suffix: cin
suffix: cmv
suffix: cpk
suffix: daud
suffix: dct
suffix: divx
suffix: dts
suffix: dv
suffix: dvd
suffix: dxa
suffix: eac3
suffix: film
suffix: flac
suffix: flc
suffix: fli
suffix: fll
suffix: flx
suffix: flv
suffix: g726
suffix: gsm
suffix: gxf
suffix: iss
suffix: m1v
suffix: m2v
suffix: m2t
suffix: m2ts
suffix: m4a
suffix: m4b
suffix: m4v
suffix: mad
suffix: mj2
suffix: mjpeg
suffix: mjpg
suffix: mka
suffix: mkv
suffix: mlp
suffix: mm
suffix: mmf
suffix: mov
suffix: mp+
suffix: mp1
suffix: mp2
suffix: mp3
suffix: mp4
suffix: mpc
suffix: mpeg
suffix: mpg
suffix: mpga
suffix: mpp
suffix: mpu
suffix: mve
suffix: mvi
suffix: mxf
suffix: nc
suffix: nsv
suffix: nut
suffix: nuv
suffix: oga
suffix: ogm
suffix: ogv
suffix: ogx
suffix: oma
suffix: ogg
suffix: omg
suffix: opus
suffix: psp
suffix: pva
suffix: qcp
suffix: qt
suffix: r3d
suffix: ra
suffix: ram
suffix: rl2
suffix: rm
suffix: rmvb
suffix: roq
suffix: rpl
suffix: rvc
suffix: shn
suffix: smk
suffix: snd
suffix: sol
suffix: son
suffix: spx
suffix: str
suffix: swf
suffix: tak
suffix: tgi
suffix: tgq
suffix: tgv
suffix: thp
suffix: ts
suffix: tsp
suffix: tta
suffix: xa
suffix: xvid
suffix: uv
suffix: uv2
suffix: vb
suffix: vid
suffix: vob
suffix: voc
suffix: vp6
suffix: vmd
suffix: wav
suffix: webm
suffix: wma
suffix: wmv
suffix: wsaud
suffix: wsvga
suffix: wv
suffix: wve
mime_type: application/flv
mime_type: application/m4a
mime_type: application/mp4
mime_type: application/octet-stream
mime_type: application/ogg
mime_type: application/x-ms-wmz
mime_type: application/x-ms-wmd
mime_type: application/x-ogg
mime_type: application/x-shockwave-flash
mime_type: application/x-shorten
mime_type: audio/8svx
mime_type: audio/16sv
mime_type: audio/aac
mime_type: audio/aacp
mime_type: audio/ac3
mime_type: audio/aiff
mime_type: audio/amr
mime_type: audio/basic
mime_type: audio/flac
mime_type: audio/m4a
mime_type: audio/mp4
mime_type: audio/mpeg
mime_type: audio/musepack
mime_type: audio/ogg
mime_type: audio/opus
mime_type: audio/qcelp
mime_type: audio/vorbis
mime_type: audio/vorbis+ogg
mime_type: audio/wav
mime_type: audio/x-8svx
mime_type: audio/x-16sv
mime_type: audio/x-aac
mime_type: audio/x-ac3
mime_type: audio/x-adx
mime_type: audio/x-aiff
mime_type: audio/x-alaw
mime_type: audio/x-au
mime_type: audio/x-dca
mime_type: audio/x-eac3
mime_type: audio/x-flac
mime_type: audio/x-gsm
mime_type: audio/x-mace
mime_type: audio/x-matroska
mime_type: audio/x-monkeys-audio
mime_type: audio/x-mpeg
mime_type: audio/x-ms-wma
mime_type: audio/x-ms-wax
mime_type: audio/x-musepack
mime_type: audio/x-ogg
mime_type: audio/x-vorbis
mime_type: audio/x-vorbis+ogg
mime_type: audio/x-pn-realaudio
mime_type: audio/x-pn-multirate-realaudio
mime_type: audio/x-speex
mime_type: audio/x-tta
mime_type: audio/x-voc
mime_type: audio/x-wav
mime_type: audio/x-wma
mime_type: audio/x-wv
mime_type: video/anim
mime_type: video/quicktime
mime_type: video/msvideo
mime_type: video/ogg
mime_type: video/theora
mime_type: video/webm
mime_type: video/x-dv
mime_type: video/x-flv
mime_type: video/x-matroska
mime_type: video/x-mjpeg
mime_type: video/x-mpeg
mime_type: video/x-ms-asf
mime_type: video/x-msvideo
mime_type: video/x-ms-wmv
mime_type: video/x-ms-wvx
mime_type: video/x-ms-wm
mime_type: video/x-ms-wmx
mime_type: video/x-nut
mime_type: video/x-pva
mime_type: video/x-theora
mime_type: video/x-vid
mime_type: video/x-wmv
mime_type: video/x-xvid
mime_type: audio/x-mpd-ffmpeg
plugin: pcm
mime_type: audio/L16
mime_type: audio/L24
mime_type: audio/x-mpd-float
mime_type: audio/x-mpd-cdda-pcm
mime_type: audio/x-mpd-cdda-pcm-reverse
mime_type: audio/x-mpd-alsa-pcm
OK
"#;
