#[cfg(target_os = "linux")]
pub mod bluetooth;
pub mod clear;
pub mod community;
pub mod login;
pub mod open;
pub mod repl;
pub mod run;
pub mod scan;
pub mod service;
pub mod setup;
pub mod start;
pub mod webui;
pub mod whoami;
