[package]
edition = "2021"
name = "rockbox-server"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.89"
async-std = {version = "1.13.0", features = ["unstable"]}
futures-util = "0.3.31"
lazy_static = "1.5.0"
local-ip-addr = "0.1.1"
md5 = "0.7.0"
owo-colors = "4.0.0"
queryst = "3.0.0"
rand = "0.8.5"
reqwest = {version = "0.12.5", features = ["blocking", "rustls-tls"], default-features = false}
rockbox-chromecast = {path = "../chromecast"}
rockbox-discovery = {path = "../discovery"}
rockbox-graphql = {path = "../graphql"}
rockbox-library = {path = "../library"}
rockbox-rocksky = {path = "../rocksky"}
rockbox-mpd = {path = "../mpd"}
rockbox-mpris = {path = "../mpris"}
rockbox-network = { path = "../network" }
rockbox-rpc = {path = "../rpc"}
rockbox-search = {path = "../search"}
rockbox-settings = {path = "../settings"}
rockbox-sys = {path = "../sys"}
rockbox-tracklist = {path = "../tracklist"}
rockbox-traits = {path = "../traits"}
rockbox-types = {path = "../types"}
serde = {version = "1.0.210", features = ["derive"]}
serde_json = "1.0.128"
sqlx = {version = "0.8.2", features = ["runtime-tokio", "tls-rustls", "sqlite", "chrono", "derive", "macros"]}
threadpool = "1.8.1"
tokio = {version = "1.36.0", features = ["full"]}
url = "2.3.1"
urlencoding = "2.1.3"
