name: cargo-fmt
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          plugin: rust
          args: setup
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run fmt
        run: |
          type cargo
          cargo fmt -p deno
          cargo fmt --all --check
