name: Import secrets and variables to Depot CI
on: push

permissions:
  id-token: write
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: depot/setup-action@v1
      - name: Import secrets
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          FURY_ACCOUNT: ${{ secrets.FURY_ACCOUNT }}
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}
        run: |
          unset DEPOT_TOKEN
          depot ci secrets add CHROMATIC_PROJECT_TOKEN="$CHROMATIC_PROJECT_TOKEN" DAGGER_CLOUD_TOKEN="$DAGGER_CLOUD_TOKEN" DOCKERHUB_PASSWORD="$DOCKERHUB_PASSWORD" DOCKERHUB_USERNAME="$DOCKERHUB_USERNAME" FURY_ACCOUNT="$FURY_ACCOUNT" FURY_TOKEN="$FURY_TOKEN" --repo tsirysndr/rockboxd
